import type { Prisma } from '@prisma/client';
import { AppError } from '../../shared/errors/app-error.js';
import * as auth from '../auth/auth.service.js';
import { presentBooking } from '../bookings/booking.presenter.js';
import { presentListing } from '../rooms/room.presenter.js';
import type { CalendarInput, ListingInput, ListingUpdateInput } from './host.dto.js';
import { hostRepository as repo } from './host.repository.js';

async function requireHost(userId: string) { const host = await repo.findByUserId(userId); if (!host) throw new AppError(403, 'FORBIDDEN', 'Bạn chưa kích hoạt hồ sơ Host'); return host; }
async function ownedListing(userId: string, listingId: string) { const host = await requireHost(userId); const listing = await repo.listing(host.id, listingId); if (!listing) throw new AppError(404, 'NOT_FOUND', 'Không tìm thấy listing'); return listing; }

export async function onboard(userId: string, sessionId?: string) { const user = await repo.findUserWithHost(userId); const host = user.hostProfile ?? await repo.createHost({ userId: user.id, name: user.name, email: user.email, phone: user.phone, avatarUrl: user.avatarUrl, about: user.bio, joinedDate: new Intl.DateTimeFormat('vi-VN', { month: 'long', year: 'numeric' }).format(new Date()), identityVerified: Boolean(user.emailVerifiedAt) }); await repo.updateUserRole(user.id); await auth.logout(sessionId); return { host, tokens: await auth.createSession(user.id, 'HOST') }; }
export async function getProfile(userId: string) { return requireHost(userId); }
export async function updateProfile(userId: string, input: { name?: string; phone?: string | null; avatarUrl?: string | null; about?: string | null; responseTime?: string }) { const host = await requireHost(userId); return repo.updateHost(host.id, input); }
export async function dashboard(userId: string) { const host = await requireHost(userId); const [bookings, activeListings] = await Promise.all([repo.dashboardBookings(host.id), repo.activeListingCount(host.id)]); return { activeListings, upcomingReservations: bookings.filter(item => item.status === 'UPCOMING').length, revenue: bookings.filter(item => item.status !== 'CANCELLED').reduce((sum, item) => sum + item.totalPrice, 0) }; }
export async function listings(userId: string) { const host = await requireHost(userId); return (await repo.listings(host.id)).map(item => presentListing(item)); }
export async function listing(userId: string, listingId: string) { return presentListing(await ownedListing(userId, listingId), true); }
export async function createListing(userId: string, input: ListingInput) { const host = await requireHost(userId); const data: Prisma.ListingUncheckedCreateInput = { hostId: host.id, name: input.name, roomType: input.roomType, city: input.city, district: input.district, neighborhood: input.neighborhood, address: input.address, latitude: input.latitude, longitude: input.longitude, pricePerNight: input.pricePerNight, priceFormatted: `${input.pricePerNight.toLocaleString('vi-VN')} ₫ / đêm`, cleaningFee: input.cleaningFee, serviceFeeRate: input.serviceFeeRate, guestsMax: input.guestsMax, bedrooms: input.bedrooms, beds: input.beds, baths: input.baths, description: input.description, coverImage: input.images[0], imageCount: input.images.length, houseRules: input.houseRules, cancellationPolicyTitle: input.cancellationPolicyTitle, cancellationPolicyDescription: input.cancellationPolicyDescription, status: input.status, images: { create: input.images.map((imageUrl, displayOrder) => ({ imageUrl, displayOrder, isCover: displayOrder === 0 })) }, amenities: { create: input.amenities.map(amenityName => ({ amenityName })) } }; return presentListing(await repo.createListing(data), true); }
export async function updateListing(userId: string, listingId: string, input: ListingUpdateInput) { const current = await ownedListing(userId, listingId); const { images, amenities, ...fields } = input; const data: Prisma.ListingUpdateInput = { ...fields, ...(input.pricePerNight !== undefined ? { priceFormatted: `${input.pricePerNight.toLocaleString('vi-VN')} ₫ / đêm` } : {}), ...(images ? { coverImage: images[0], imageCount: images.length, images: { deleteMany: {}, create: images.map((imageUrl, displayOrder) => ({ imageUrl, displayOrder, isCover: displayOrder === 0 })) } } : {}), ...(amenities ? { amenities: { deleteMany: {}, create: amenities.map(amenityName => ({ amenityName })) } } : {}) }; return presentListing(await repo.updateListing(current.id, data), true); }
export async function setListingStatus(userId: string, listingId: string, status: 'DRAFT' | 'ACTIVE' | 'INACTIVE') { const current = await ownedListing(userId, listingId); return presentListing(await repo.updateListingStatus(current.id, status)); }
export async function removeListing(userId: string, listingId: string) { await setListingStatus(userId, listingId, 'INACTIVE'); }
export async function reservations(userId: string) { const host = await requireHost(userId); return (await repo.reservations(host.id)).map(presentBooking); }
export async function reservation(userId: string, id: string) { const host = await requireHost(userId); const booking = await repo.reservation(host.id, id); if (!booking) throw new AppError(404, 'NOT_FOUND', 'Không tìm thấy booking'); return presentBooking(booking); }
export async function calendar(userId: string, listingId: string) { const host = await requireHost(userId); const listing = await repo.listingCalendar(host.id, listingId); if (!listing) throw new AppError(404, 'NOT_FOUND', 'Không tìm thấy listing'); return listing.calendar; }
export async function createCalendar(userId: string, listingId: string, input: CalendarInput) { const listing = await ownedListing(userId, listingId); const checkIn = new Date(input.checkIn), checkOut = new Date(input.checkOut); if (await repo.calendarConflict(listing.id, checkIn, checkOut)) throw new AppError(409, 'DATES_UNAVAILABLE', 'Khoảng thời gian đã bị chặn'); return repo.createCalendar({ listingId: listing.id, checkIn, checkOut, isBlocked: input.isBlocked, priceOverride: input.priceOverride, note: input.note }); }
export async function updateCalendar(userId: string, listingId: string, calendarId: string, input: CalendarInput) { const listing = await ownedListing(userId, listingId); const existing = await repo.editableCalendar(listing.id, calendarId); if (!existing) throw new AppError(404, 'NOT_FOUND', 'Không tìm thấy lịch Host có thể sửa'); const checkIn = new Date(input.checkIn), checkOut = new Date(input.checkOut); if (await repo.calendarConflict(listing.id, checkIn, checkOut, existing.id)) throw new AppError(409, 'DATES_UNAVAILABLE', 'Khoảng thời gian đã bị chặn'); return repo.updateCalendar(existing.id, { checkIn, checkOut, isBlocked: input.isBlocked, priceOverride: input.priceOverride, note: input.note }); }
export async function removeCalendar(userId: string, listingId: string, calendarId: string) { const listing = await ownedListing(userId, listingId); const result = await repo.deleteCalendar(listing.id, calendarId); if (!result.count) throw new AppError(404, 'NOT_FOUND', 'Không tìm thấy lịch Host có thể xóa'); }
