import { Router } from 'express';
import { authorize, requireAuth } from '../auth/auth.middleware.js';
import * as controller from './host.controller.js';
import { createListingRateLimiter } from './host.rate-limit.js';
export const hostRouter = Router();
hostRouter.post('/hosts/onboarding', requireAuth, controller.onboard);
hostRouter.get('/hosts/me', requireAuth, authorize('HOST'), controller.getProfile);
hostRouter.patch('/hosts/me', requireAuth, authorize('HOST'), controller.updateProfile);
hostRouter.use('/host', requireAuth, authorize('HOST'));
hostRouter.get('/host/dashboard', controller.dashboard);
hostRouter.get('/host/listings', controller.listings);
hostRouter.get('/host/listings/:listingId', controller.listing);
hostRouter.post('/host/listings', createListingRateLimiter, controller.createListing);
hostRouter.patch('/host/listings/:listingId', controller.updateListing);
hostRouter.patch('/host/listings/:listingId/status', controller.setStatus);
hostRouter.delete('/host/listings/:listingId', controller.removeListing);
hostRouter.get('/host/reservations', controller.reservations);
hostRouter.get('/host/reservations/:bookingId', controller.reservation);
hostRouter.get('/host/listings/:listingId/calendar', controller.calendar);
hostRouter.post('/host/listings/:listingId/calendar', controller.createCalendar);
hostRouter.patch('/host/listings/:listingId/calendar/:calendarId', controller.updateCalendar);
hostRouter.delete('/host/listings/:listingId/calendar/:calendarId', controller.removeCalendar);
